//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperHelp_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.AssFiles = new HashSet<AssFile>();
        }
    
        public int ID { get; set; }
        public string ClientId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<bool> IsNormal { get; set; }
        public Nullable<int> NoOfPaper { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<byte> duration { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> finishedDate { get; set; }
        public string ClientNote { get; set; }
        public string Description { get; set; }
        public string writerId { get; set; }
        public string ProfreaderId { get; set; }
        public string FinalFilePath { get; set; }
        public string ProfraderNotes { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssFile> AssFiles { get; set; }
        public virtual Service Service { get; set; }
    }
}
